# Generated by Django 2.1.5 on 2019-04-06 01:58

from django.db import migrations, models
import django.db.models.deletion
import roster.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('stat', models.CharField(max_length=30)),
                ('shot_location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('opponent', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('team_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('lineup_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='roster.Lineup')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='roster.Lineup')),
            ],
        ),
        migrations.CreateModel(
            name='LineupScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp_entered', models.DateTimeField()),
                ('time_stamp_left', models.DateTimeField()),
                ('team_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Game')),
                ('lineup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Lineup')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_num', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('screen_for', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[(roster.models.PlayerPosition('Point Guard'), 'PG'), (roster.models.PlayerPosition('Shooting Guard'), 'SG'), (roster.models.PlayerPosition('Small Forward'), 'SF'), (roster.models.PlayerPosition('Power Forward'), 'PF'), (roster.models.PlayerPosition('Center'), 'C')], max_length=2)),
                ('year_in_school', models.CharField(choices=[(roster.models.YearInSchool('Freshman'), 'FR'), (roster.models.YearInSchool('Sophomore'), 'SO'), (roster.models.YearInSchool('Junior'), 'JR'), (roster.models.YearInSchool('Senior'), 'SR')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Coach')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Team'),
        ),
        migrations.AddField(
            model_name='play',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Team'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='roster.Player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='point_guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_guard', to='roster.Player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='power_forward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_forward', to='roster.Player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='shooting_guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shooting_guard', to='roster.Player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='small_forward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_forward', to='roster.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Team'),
        ),
        migrations.AddField(
            model_name='basketballstat',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Game'),
        ),
        migrations.AddField(
            model_name='basketballstat',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Player'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Player'),
        ),
    ]
