# Generated by Django 2.1.5 on 2019-02-15 23:24

from django.db import migrations, models
import roster.models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='year_in_school',
            field=models.CharField(choices=[(roster.models.YearInSchool('Freshman'), 'FR'), (roster.models.YearInSchool('Sophomore'), 'SO'), (roster.models.YearInSchool('Junior'), 'JR'), (roster.models.YearInSchool('Senior'), 'SR')], default='null', max_length=2),
            preserve_default=False,
        ),
    ]
