# Generated by Django 2.1.5 on 2019-04-18 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roster.models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='no name', max_length=100)),
                ('last_name', models.CharField(default='no name', max_length=100)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[(roster.models.PlayerPosition('Point Guard'), 'PG'), (roster.models.PlayerPosition('Shooting Guard'), 'SG'), (roster.models.PlayerPosition('Small Forward'), 'SF'), (roster.models.PlayerPosition('Power Forward'), 'PF'), (roster.models.PlayerPosition('Center'), 'C')], max_length=2)),
                ('year_in_school', models.CharField(choices=[(roster.models.YearInSchool('Freshman'), 'FR'), (roster.models.YearInSchool('Sophomore'), 'SO'), (roster.models.YearInSchool('Junior'), 'JR'), (roster.models.YearInSchool('Senior'), 'SR')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Coach')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roster.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
