# Generated by Django 2.1.5 on 2019-04-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_auto_20190418_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.CharField(default='coach', max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_name',
            field=models.CharField(default='coach', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Team'),
        ),
    ]
