# Generated by Django 2.1.5 on 2019-04-18 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20190418_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='roster.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=18, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='roster.Coach'),
        ),
    ]
