# Generated by Django 2.1.5 on 2019-04-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_auto_20190419_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
    ]
